CREATE TABLE APARTMENTS (
  ID      INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  REGION  VARCHAR(255) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  SQUARE  INT          NOT NULL,
  ROOMS   INT          NOT NULL,
  PRICE   DOUBLE       NOT NULL
)